name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  APP_NAME: fastapi-app
  ENV_NAME: prod
  SVC_NAME: fastapi-svc

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::885812045782:role/awscopilot-oidc
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Create ECR repository if it doesn't exist
          aws ecr describe-repositories --repository-names ${{ env.APP_NAME }} || aws ecr create-repository --repository-name ${{ env.APP_NAME }}
          
          # Build and push image
          docker build -t $ECR_REGISTRY/${{ env.APP_NAME }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.APP_NAME }}:$IMAGE_TAG
          
          # Tag as latest
          docker tag $ECR_REGISTRY/${{ env.APP_NAME }}:$IMAGE_TAG $ECR_REGISTRY/${{ env.APP_NAME }}:latest
          docker push $ECR_REGISTRY/${{ env.APP_NAME }}:latest
      
      - name: Install AWS Copilot CLI
        run: |
          curl -Lo copilot-cli https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x copilot-cli
          sudo mv copilot-cli /usr/local/bin/copilot
      
      - name: Create workspace file
        run: |
          # Create .copilot directory if it doesn't exist
          mkdir -p .copilot
          # Create the workspace file with the application name
          echo "{\"application\": \"${{ env.APP_NAME }}\"}" > .copilot/.workspace
      
      - name: Deploy with Copilot
        run: |
          # Initialize app in AWS if it doesn't exist (this won't modify local files)
          copilot app init ${{ env.APP_NAME }} --resource-tags project=${{ env.APP_NAME }} || true
          
          # Initialize environment if it doesn't exist
          copilot env ls --app ${{ env.APP_NAME }} | grep -q "${{ env.ENV_NAME }}" || \
            (copilot env init --name ${{ env.ENV_NAME }} --app ${{ env.APP_NAME }} --profile default --default-config && \
             copilot env deploy --name ${{ env.ENV_NAME }} --app ${{ env.APP_NAME }})
          
          # Deploy service using existing manifest
          copilot svc deploy --name ${{ env.SVC_NAME }} --env ${{ env.ENV_NAME }} --tag ${{ github.sha }}
      
      - name: Show service URL
        if: success()
        run: |
          echo "Service deployed successfully! Endpoint URL:"
          copilot svc show --name ${{ env.SVC_NAME }} --app ${{ env.APP_NAME }} --env ${{ env.ENV_NAME }} --json | jq -r '.routes[0].url'
