name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::885812045782:role/awscopilot-oidc
          aws-region: us-east-1
      
      - name: Create ECR repository if it doesn't exist
        run: |
          aws ecr describe-repositories --repository-names fastapi-app || aws ecr create-repository --repository-name fastapi-app
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fastapi-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      
      - name: Install AWS Copilot CLI
        run: |
          # Remove existing copilot directory if it exists
          rm -rf copilot-cli-temp
          # Download to a temporary file
          curl -Lo copilot-cli-temp https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x copilot-cli-temp
          sudo mv copilot-cli-temp /usr/local/bin/copilot
          copilot --version
      
      - name: Initialize and deploy with AWS Copilot
        run: |
          # Initialize the application if it doesn't exist
          copilot app init --domain fastapi-app --resource-tags project=fastapi-demo || true
          
          # Check if environment exists, create if it doesn't
          copilot env show --name prod || copilot env init --name prod --profile default --default-config
          
          # Deploy the service
          copilot svc deploy --name fastapi-svc --env prod
