name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  APP_NAME: fastapi-app
  ENV_NAME: prod
  SVC_NAME: fastapi-svc

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::885812045782:role/awscopilot-oidc
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Create ECR repository if needed
          aws ecr describe-repositories --repository-names ${{ env.APP_NAME }} || aws ecr create-repository --repository-name ${{ env.APP_NAME }}
          
          # Build and push image
          docker build -t $ECR_REGISTRY/${{ env.APP_NAME }}:${{ github.sha }} .
          docker push $ECR_REGISTRY/${{ env.APP_NAME }}:${{ github.sha }}
      
      - name: Install AWS Copilot CLI
        run: |
          curl -Lo copilot-cli https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x copilot-cli
          sudo mv copilot-cli /usr/local/bin/copilot
      
      - name: Deploy with AWS Copilot
        run: |
          # Initialize app if it doesn't exist
          copilot app init ${{ env.APP_NAME }} --resource-tags project=fastapi-demo || true
          
          # Initialize environment if it doesn't exist
          copilot env init --name ${{ env.ENV_NAME }} --app ${{ env.APP_NAME }} --default-config || true
          
          # Initialize service if it doesn't exist
          copilot svc init --name ${{ env.SVC_NAME }} --app ${{ env.APP_NAME }} --svc-type "Load Balanced Web Service" --dockerfile ./Dockerfile || true
          
          # Deploy the service
          copilot svc deploy --name ${{ env.SVC_NAME }} --env ${{ env.ENV_NAME }} --app ${{ env.APP_NAME }}
